### ISSUE TITLE
JSON: i campi a null che mappano su BaseClassSerializable non dovrebbero essere deserializzati

### ISSUE THREAD

**Issue by dieric** [FatturaElettronica/FatturaElettronica.Core#17] opened 2019-01-16 13:43 UTC
Ho seguito i passi indicati nel doc di esempio per validare il mio oggetto fattura prima di salvarlo su file.
Ma quando eseguo validator.validate(fattura) va in errore "Object reference not set to an instance of an object".
Ho verificato di avere le ultime versioni disponibili sia dei pacchetti.

Preciso che lavoro in vb.net ma non credo sia questo il problema.

Suggerimenti?

Grazie
Diego

**Comment by nicolaiarocci** [comment] 2019-03-07 16:22
@dieric non mettere a null (`Nothing` in VB) le proprietà di tipo `BaseClassSerializable` (praticamente tutte le proprietà di tipo oggetto)

@liborpansky  got it.

**Comment by nicolaiarocci** [comment] 2019-03-07 16:27
@liborpansky should be fixed. Care to try it before I release the package?

**Closed** 2019-03-07 16:27 UTC

**Comment by liborpansky** [comment] 2019-03-07 18:30
I've just tried it and I guess the problem is in fluent validation rules.
Let's say I try to create a basic example (already 2.0 beta code):
```C#
FatturaOrdinaria fattura = new FatturaOrdinaria
{
    FatturaElettronicaHeader = new FatturaElettronica.Ordinaria.FatturaElettronicaHeader.FatturaElettronicaHeader
    {
        DatiTrasmissione = new FatturaElettronica.Ordinaria.FatturaElettronicaHeader.DatiTrasmissione.DatiTrasmissione
        {
            ContattiTrasmittente = null
        }
    }
};

FatturaOrdinariaValidator invoiceValidator = new FatturaOrdinariaValidator();
var result = invoiceValidator.Validate(fattura);
```

Logic result for me would be following messages:
FatturaElettronicaHeader.DatiTrasmissione.IdTrasmittente is required
FatturaElettronicaHeader.DatiTrasmissione.ProgressivoInvio is required
FatturaElettronicaHeader.DatiTrasmissione.FormatoTrasmissione is required
FatturaElettronicaHeader.DatiTrasmissione.CodiceDestinatario is required
FatturaElettronicaHeader.CedentePrestatore is required
At least 1 FatturaElettronicaBody is required

but current validation result is 23 messages (inner details, not base level objects).

If I replace `ContattiTrasmittenteValidator` in `DatiTrasmissioneValidator` from
```C#
RuleFor(dt => dt.ContattiTrasmittente)
    .SetValidator(new ContattiTrasmittenteValidator())
    .When(x => !x.ContattiTrasmittente.IsEmpty());
```
to 
```C#
RuleFor(dt => dt.ContattiTrasmittente)
  .SetValidator(new ContattiTrasmittenteValidator())
  .When(x => x != null);
```

I won't get a null reference exception anymore...

**Comment by nicolaiarocci** [comment] 2019-03-07 19:16
Hmm v2.0-beta still has to be updated with latest Core, so you're probably not using the right version of Core. Be back soon.

**Comment by nicolaiarocci** [comment] 2019-03-07 20:43
PS: yes that's also an option since we have public setters for those instance properties. Would also solve @dieric issue most likely (I'm just assuming here since we don't know how he got into that situation). My current approach is not letting the JSON de-serializer not set those properties to null, to align its behaviour with XML de-serializer (well xml is a different story of course, but you get the point: you won't get a null property instance by de-serializing a file with missing fields).

**Comment by liborpansky** [comment] 2019-03-08 06:14
Change default JSON serializer settings would certainly help, but it's against default ASP.NET Core Web API serializer settings and sometimes a null value is correct value I expect to be set on object - I don't want to replace it with a new object instance.

I have directly exposed your Fattura model in API, so I should either:

- change default serializer settings for invoice endpoints, but risk additional problems connected with change of this behavior,
- change fluent validation rules for Fattura object directly in your library,
- create a custom validators.

Problem is that in current situation user receives a 500 response instead of 400 with a list of missing required fields on object.

I'm not sure if this modifications directly in FatturaElettronica would change some expected behavior for your current users (considering that it's used for both XML and JSON).

**Comment by nicolaiarocci** [comment] 2019-03-08 07:28
Got it. I think I'm reverting the de-serializer in Core, and then fix the validators as per your suggestion.

**Comment by nicolaiarocci** [comment] 2019-03-08 08:36
```cs
RuleFor(dt => dt.ContattiTrasmittente)
  .SetValidator(new ContattiTrasmittenteValidator())
  .When(x => x != null && !x.ContattiTrasmittente.IsEmpty());
```

Should be the best approach.

**Comment by nicolaiarocci** [comment] 2019-03-08 09:07
amended
